# **Performing Naive Bayes on tips dataset**

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('tips')

In [3]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [5]:
X = df[['total_bill', 'tip', 'sex', 'day', 'time', 'size']]

In [6]:
y=df[['smoker']]

In [7]:
X

     total_bill   tip     sex   day    time  size
0         16.99  1.01  Female   Sun  Dinner     2
1         10.34  1.66    Male   Sun  Dinner     3
2         21.01  3.50    Male   Sun  Dinner     3
3         23.68  3.31    Male   Sun  Dinner     2
4         24.59  3.61  Female   Sun  Dinner     4
..          ...   ...     ...   ...     ...   ...
239       29.03  5.92    Male   Sat  Dinner     3
240       27.18  2.00  Female   Sat  Dinner     2
241       22.67  2.00    Male   Sat  Dinner     2
242       17.82  1.75    Male   Sat  Dinner     2
243       18.78  3.00  Female  Thur  Dinner     2

[244 rows x 6 columns]

In [8]:
y

    smoker
0       No
1       No
2       No
3       No
4       No
..     ...
239     No
240    Yes
241    Yes
242     No
243     No

[244 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y, test_size=0.25, random_state=10)

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [11]:
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [12]:
y_train

array([1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0])

In [13]:
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [14]:
X_train['sex']=le1.fit_transform(X_train['sex'])
X_train['day'] = le2.fit_transform(X_train['day'])
X_train['time']=le3.fit_transform(X_train['time'])

X_test['sex']=le1.transform(X_test['sex'])
X_test['day'] = le2.transform(X_test['day'])
X_test['time']=le3.transform(X_test['time'])

In [15]:
from sklearn.naive_bayes import GaussianNB

In [16]:
gnb = GaussianNB()

In [17]:
gnb.fit(X_train,y_train)

GaussianNB()

In [18]:
y_pred = gnb.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix

In [20]:
acs=  accuracy_score(y_test, y_pred)
clr=classification_report(y_test,y_pred)
cm=confusion_matrix(y_test,y_pred)
print("accurancy score: \n",acs)
print('confusion matrix\n',cm)
print('classification report:\n',clr)

accurancy score:
 0.6229508196721312
confusion matrix
 [[26  7]
 [16 12]]
classification report:
               precision    recall  f1-score   support

           0       0.62      0.79      0.69        33
           1       0.63      0.43      0.51        28

    accuracy                           0.62        61
   macro avg       0.63      0.61      0.60        61
weighted avg       0.62      0.62      0.61        61

Testing on New Data

In [21]:
new_data = [[20.5, 3.5, 1, 2, 0, 2]]
prediction = gnb.predict(new_data)

c:\Users\prash\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [22]:
print(prediction)

[0]

Convert the prediction back to the original label

In [23]:
result = le.inverse_transform(prediction)
print(result)

['No']